mastaky/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:painting_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:painting_id>/', views.cart_remove, name='cart_remove'),
    path('order/', views.order_create, name='order'),
    path('order_success/', views.order_success, name='order_success')
]

mastaky/mastaky/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('painting/', include('painting.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
    path('signup/', include('signup.urls')),
    #path('accounts/', include('django.contrib.auth.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mastaky/painting/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.painting_index, name='painting_index'),
   path('painting/<int:painting_id>/', views.painting_detail, name='painting_detail')
]

mastaky/painting/models.py
from django.db import models


class Painting(models.Model):
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=50)
    image = models.ImageField(upload_to='paintings/')
    price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)

    def __str__(self):
        return self.title


class AboutPainting(models.Model):
    painting = models.OneToOneField(Painting, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField()
    image1 = models.ImageField(upload_to='painting_details/')
    image2 = models.ImageField(upload_to='painting_details/')
    image3 = models.ImageField(upload_to='painting_details/')
    image4 = models.ImageField(upload_to='painting_details/')
    price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)

    def __str__(self):
        return self.title

mastaky/painting/views.py
from django.shortcuts import render
from . import models


def painting_index(request):
    all_paintings = models.Painting.objects.all()
    context = {
        'all_paintings': all_paintings
    }
    return render(request, 'painting_index.html', context)


def painting_detail(request, painting_id):
    painting = models.Painting.objects.get(pk=painting_id)
    about_painting = models.AboutPainting.objects.get(painting=painting)
    context = {
        'painting': painting,
        'about_painting': about_painting
    }

    return render(request, 'painting_detail.html', context)

mastaky/painting/templates/painting_detail.html
{% extends 'base.html' %}

{% block content %}
<nav class="navigation">
            <div class="container">
                <ul>
                    <li class="home"><a href="{% url 'main_index' %}"><div class="home-image"><i class="fa fa-home"></i></div></a></li>
                    <li class="tel"><a href="#">+375 29 8139716</a></li>
                </ul>
            </div>
</nav>
<main class="main">
    <div class="container">
        <div class="painting-detail">
            <img class="main-image" src="{{ painting.image.url }}" alt="photo painting"> <!-- Перемещено влево -->
            <div class="details">
                <h1>{{ painting.title }}</h1>
                <h2>Автор: {{ painting.artist }}</h2>
                <h3>Цена: {{ painting.price }}</h3>
                <div class="about-painting">
                    <h2>{{ about_painting.title }}</h2>
                    <p>{{ about_painting.description }}</p>
                    <h3>Дополнительная цена: {{ about_painting.price }}</h3>
                </div>
                <form action="{% url 'cart:cart_add' painting_id=painting.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Добавить в корзину">
                </form>
            </div>
        </div>
        <div class="additional-images">
            <img src="{{ about_painting.image1.url }}" alt="additional image 1">
            <img src="{{ about_painting.image2.url }}" alt="additional image 2">
            <img src="{{ about_painting.image3.url }}" alt="additional image 3">
            <img src="{{ about_painting.image4.url }}" alt="additional image 4">
        </div>
    </div>
</main>
{% endblock %}

mastaky/painting/templates/painting_index.html
{% extends 'base.html' %}
{% block content %}
<nav class="navigation">
            <div class="container">
                <ul>
                    <li class="home"><a href="{% url 'main_index' %}"><div class="home-image"><i class="fa fa-home"></i></div></a></li>
                    <li class="tel"><a href="#">+375 29 8139716</a></li>
                </ul>
            </div>
</nav>
<main class="main">
    <div class="container">

        <div class="paintings">
            <h1>Картины</h1>
            {% for item in all_paintings %}
            <div class="paintings_item">
                <div class="image_paint_container"><img src="{{item.image.url}}" alt="photo painting"></div>
                <a href="{% url 'painting_detail' painting_id=item.id %}">{{ item.title }}</a>
                <h1>{{item.price}}</h1><br>
                <p>{{item.artist}}</p>
                <form action="{% url 'cart:cart_add' painting_id=item.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Добавить в корзину">
                </form>
            </div>
            {%endfor%}

        </div>
    </div>
</main>

{% endblock %}