mastaky/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:painting_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:painting_id>/', views.cart_remove, name='cart_remove'),
    path('order/', views.order_create, name='order'),
    path('order_success/', views.order_success, name='order_success')
]

mastaky/mastaky/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('painting/', include('painting.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
    path('signup/', include('signup.urls')),
    #path('accounts/', include('django.contrib.auth.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mastaky/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from painting.models import Painting


class Order(models.Model):
    PAYMENT_METHOD_CHOICES = [
        ('cash', 'Наличными при получении'),
        ('erip', 'Через систему ЕРИП'),
    ]

    DELIVERY_METHOD_CHOICES = [
        ('pickup', 'Самовывоз'),
        ('post', 'Почта'),
        ('courier', 'Курьер'),
    ]

    DELIVERY_TIME_CHOICES = [
        ('morning', 'Утро'),
        ('afternoon', 'День'),
        ('evening', 'Вечер'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    comment = models.TextField(blank=True, null=True)
    payment_method = models.CharField(max_length=10, choices=PAYMENT_METHOD_CHOICES)
    delivery_method = models.CharField(max_length=10, choices=DELIVERY_METHOD_CHOICES)
    delivery_date = models.DateField()
    delivery_time = models.CharField(max_length=10, choices=DELIVERY_TIME_CHOICES)

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    painting = models.ForeignKey(Painting, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.painting.title} for order {self.order.id}"

mastaky/cart/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name', 'last_name', 'address', 'phone', 'comment',
            'payment_method', 'delivery_method', 'delivery_date', 'delivery_time'
        ]
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'address': 'Адрес',
            'phone': 'Телефон',
            'comment': 'Комментарий',
            'payment_method': 'Способ оплаты',
            'delivery_method': 'Способ доставки',
            'delivery_date': 'Дата доставки',
            'delivery_time': 'Время доставки',
        }
        widgets = {
            'delivery_date': forms.SelectDateWidget(),
            'delivery_time': forms.Select(choices=Order.DELIVERY_TIME_CHOICES),
            'payment_method': forms.RadioSelect(choices=Order.PAYMENT_METHOD_CHOICES),
            'delivery_method': forms.RadioSelect(choices=Order.DELIVERY_METHOD_CHOICES),
        }

mastaky/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from painting import models
from .cart import Cart
from .forms import OrderForm
from .models import Order, OrderItem


@require_POST
def cart_add(request, painting_id):
    cart = Cart(request)
    painting = get_object_or_404(models.Painting, id=painting_id)
    cart.add(painting=painting)
    return redirect('cart:cart_detail')


def cart_remove(request, painting_id):
    cart = Cart(request)
    painting = get_object_or_404(models.Painting, id=painting_id)
    cart.remove(painting)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'detail.html', {'cart': cart})


@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    painting=item['painting'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            cart.clear()  # Очистка корзины после создания заказа
            return redirect('cart:order_success')
    else:
        form = OrderForm()
    return render(request, 'order.html', {'form': form, 'cart': cart})


def order_success(request):
    return render(request, 'order_success.html')

mastaky/cart/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<nav class="navigation">
    <div class="container">
        <ul>
            <li class="home"><a href="{% url 'main_index' %}"><div class="home-image"><i class="fa fa-home"></i></div></a></li>
            <li class="tel"><a href="#">+375 29 8139716</a></li>
            <li><a href="{% url 'painting_index' %}">карціны</a></li>
        </ul>
    </div>
</nav>
<main class="main">
    <div class="container">
        <div class="cart">
            <h3>Корзина</h3><br>
            <table class="cart-table">
                <thead>
                    <tr>
                        <th>изображение</th>
                        <th>Название</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th>общая цена</th>
                        <th>Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                    <tr>
                        <td> <img src="{{ item.painting.image.url }}" alt="{{ item.painting.title }}"></td>
                        <td>{{ item.painting.title }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.price }}</td>
                        <td>{{ item.total_price }}</td>
                        <td class="cart-item-actions">
                            <a href="{% url 'cart:cart_remove' item.painting.id %}"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p class="total-price">Общая стоимость: {{ cart.get_total_price }}</p>
            {% if user.is_authenticated %}
        <form method="post" action="{% url 'cart:order' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Оформить заказ</button>
        </form>
        {% else %}
        <p>Пожалуйста, <a href="{% url 'login' %}">войдите</a>, чтобы оформить заказ.</p>
        {% endif %}

        </div>
    </div>
</main>
{% endblock %}

mastaky/cart/templates/order.html
{% extends 'base.html' %}

{% block content %}
<nav class="navigation">
    <div class="container">
        <ul>
            <li class="home"><a href="{% url 'main_index' %}"><div class="home-image"><i class="fa fa-home"></i></div></a></li>
            <li class="tel"><a href="#">+375 29 8139716</a></li>
            <li><a href="{% url 'painting_index' %}">карціны</a></li>
            <li class="cart"><a href="{% url 'cart:cart_detail' %}"><div class="cart-image"><i class="fa fa-shopping-cart"></i></div></a></li>
        </ul>
    </div>
</nav>
<main class="main">
    <div class="container">
        <div class="order">

            <h2>Оформление заказа</h2><br>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.first_name.label_tag }}
                    {{ form.first_name }}<br>
                    {{ form.last_name.label_tag }}
                    {{ form.last_name }}<br>
                    {{ form.address.label_tag }}
                    {{ form.address }}<br>
                    {{ form.phone.label_tag }}
                    {{ form.phone }}<br>
                    {{ form.comment.label_tag }}
                    {{ form.comment }}<br>
                </div>
                <div class="form-group">
                    {{ form.payment_method.label_tag }}
                    {{ form.payment_method }}
                </div>
                <div class="form-group">
                    {{ form.delivery_method.label_tag }}
                    {{ form.delivery_method }}
                </div>
                <div class="form-group">
                    {{ form.delivery_date.label_tag }}
                    {{ form.delivery_date }}
                </div>
                <div class="form-group">
                    {{ form.delivery_time.label_tag }}
                    {{ form.delivery_time }}
                </div>
                <button type="submit" class="yellow_button">Подтвердить заказ</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

mastaky/cart/templates/order_success.html
{% extends 'base.html' %}

{% block content %}
<nav class="navigation">
    <div class="container">
        <ul>
            <li class="home"><a href="{% url 'main_index' %}"><div class="home-image"><i class="fa fa-home"></i></div></a></li>
            <li class="tel"><a href="#">+375 29 8139716</a></li>
            <li><a href="{% url 'painting_index' %}">карціны</a></li>
        </ul>
    </div>
</nav>
<main class="main">
    <div class="container">
        <div class="order">
    <h2>Ваш заказ успешно оформлен!</h2>
    <a href="{% url 'main_index' %}">Вернуться на главную</a>
        </div>
    </div>
</main>
{% endblock %}